const VARS = {
	"-10000": 		[10,	"$",	"ro",	"g",	"Random integer, very large range."],
	"-9999": 		[10,	"%",	"ro",	"g",	"Random float from 0.0f to 1.0f."],
	"-9998": 		[10,	"%",	"ro",	"g",	"Random float from -pi to pi."],
	"-9997": 		[10,	"%",	"ro",	"l",	"Final X position of the enemy."],
	"-9996": 		[10,	"%",	"ro",	"l",	"Final Y position of the enemy."],
	"-9995": 		[10,	"%",	"ro",	"l",	"Absolute X position of the enemy."],
	"-9994": 		[10,	"%",	"ro",	"l",	"Absolute Y position of the enemy."],
	"-9993": 		[10,	"%",	"ro",	"l",	"Relative X position of the enemy."],
	"-9992": 		[10,	"%",	"ro",	"l",	"Relative Y position of the enemy."],
	"-9991": 		[10,	"%",	"ro",	"g",	"Player's X position."],
	"-9990": 		[10,	"%",	"ro",	"g",	"Player's Y position."],
	"-9989": 		[10,	"%",	"ro",	"l",	"Angle from the enemy to the player."],
	"-9988": 		[10,	"$",	"ro",	"l",	"Time elapsed since the enemy spawned, in frames."],
	"-9987": 		[10,	"%",	"ro",	"g",	"Random float from -1.0f to 1.0f."],
	"-9986": 		[10,	"$",	"ro",	"g",	"Set to 1 by the engine when a timeout occurs."],
	"-9985": 		[10,	"$",	"rw",	"l",	"Local integer variable, inherited by spawned enemies."],
	"-9984": 		[10,	"$",	"rw",	"l",	"Local integer variable, inherited by spawned enemies."],
	"-9983": 		[10,	"$",	"rw",	"l",	"Local integer variable, inherited by spawned enemies."],
	"-9982": 		[10,	"$",	"rw",	"l",	"Local integer variable, inherited by spawned enemies."],
	"-9981": 		[10,	"%",	"rw",	"l",	"Local float variable, inherited by spawned enemies."],
	"-9980": 		[10,	"%",	"rw",	"l",	"Local float variable, inherited by spawned enemies."],
	"-9979": 		[10,	"%",	"rw",	"l",	"Local float variable, inherited by spawned enemies."],
	"-9978": 		[10,	"%",	"rw",	"l",	"Local float variable, inherited by spawned enemies."],
	"-9977": 		[10,	"%",	"ro",	"l",	"Same as FINAL_X?"],
	"-9976": 		[10,	"%",	"ro",	"l",	"Same as FINAL_Y?"],
	"-9975": 		[10,	"%",	"ro",	"l",	"Same as ABS_X?"],
	"-9974": 		[10,	"%",	"ro",	"l",	"Same as ABS_Y?"],
	"-9973": 		[10,	"%",	"ro",	"l",	"Same as REL_X?"],
	"-9972": 		[10,	"%",	"ro",	"l",	"Same as REL_Y?"],
	"-9971": 		[10,	"%",	"ro",	"l",	"Angle of enemy's absolute movement."],
	"-9970": 		[10,	"%",	"ro",	"l",	"Angle of enemy's relative movement."],
	"-9969": 		[10,	"%",	"ro",	"l",	"Speed of enemy's absolute movement."],
	"-9968": 		[10,	"%",	"ro",	"l",	"Speed of enemy's relative movement."],
	"-9967": 		[10,	"%",	"ro",	"l",	"Distance from the origin of enemy's absolute circular movement (radius of the circle)."],
	"-9966": 		[10,	"%",	"ro",	"l",	"Distance from the origin of enemy's relative circular movement (radius of the circle)."],
	"-9965": 		[10,	"%",	"ro",	"g",	"Same as PLAYER_X?"],
	"-9964": 		[10,	"%",	"ro",	"g",	"Same as PLAYER_Y?"],
	"-9963": 		[10,	"%",	"ro",	"g",	"Final X position of the boss."],
	"-9962": 		[10,	"%",	"ro",	"g",	"Final Y position of the boss."],
	"-9961": 		[10,	"$",	"ro",	"g",	"Unknown variable."],
	"-9960": 		[10,	"$",	"ro",	"g",	"TODO: check what this actually is."],
	"-9959": 		[10,	"$",	"ro",	"g",	"Difficulty (E=0, N=1, H=2, L=3, EX=4, O=5)"],
	"-9958": 		[10,	"%",	"ro",	"l",	"Final angle of enemy's movement."],
	"-9957": 		[10,	"$",	"ro",	"g",	"Always set to 1?"],
	"-9956": 		[10,	"%",	"ro",	"l",	"Angle to the player from enemy's absolute position."],
	"-9955": 		[10,	"%",	"ro",	"l",	"Angle to the player from enemy's relative position."],
	"-9954": 		[10,	"$",	"ro",	"l",	"Enemy's current HP."],
	"-9953": 		[10,	"$",	"ro",	"g",	"Set to 1 if difficulty is easy, othewise it's 0."],
	"-9952": 		[10,	"$",	"ro",	"g",	"Set to 1 if difficulty is normal, othewise it's 0."],
	"-9951": 		[10,	"$",	"ro",	"g",	"Set to 1 if difficulty is hard, othewise it's 0."],
	"-9950": 		[10,	"$",	"ro",	"g",	"Set to 1 if difficulty is lunatic, othewise it's 0."],
	"-9949": 		[11,	"$",	"rw",	"g",	"Increased by 1 every time the player dies."],
	"-9948": 		[11,	"$",	"rw",	"g",	"Increased by 1 every time the player bombs."],
	"-9947": 		[11,	"$",	"rw",	"g",	"Set to 0 when the player dies, bombs, or uses a game-specific mechanic that \"fails\" a spell."],
	"-9946": 		[11,	"$",	"ro",	"g",	"Amount of enemies alive (including main and MapleEnemy)."],
	"-9945": 		[11,	"$",	"ro",	"g",	"Numeric value that represents player's shottype, the first shottype is 0."],
	"-9944": 		[11,	"%",	"ro",	"l",	"Distance from the enemy to the player."],
	"-9943": 		[11,	"$",	"rw",	"l",	"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9942": 		[11,	"$",	"rw",	"l",	"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9941": 		[11,	"$",	"rw",	"l",	"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9940": 		[11,	"$",	"rw",	"l",	"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9939": 		[11,	"%",	"rw",	"l",	"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9938": 		[11,	"%",	"rw",	"l",	"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9937": 		[11,	"%",	"rw",	"l",	"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9936": 		[11,	"%",	"rw",	"l",	"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9935": 		[11,	"%",	"rw",	"l",	"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9934": 		[11,	"%",	"rw",	"l",	"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9933": 		[11,	"%",	"rw",	"l",	"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9932": 		[11,	"%",	"rw",	"l",	"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9931": 		[12,	"$",	"ro",	"g",	"ID of the last spawned enemy."],
	"-9930": 		[12,	"$",	"ro",	"g",	"Player's power (4.00 => 400)"],
	"-9929": 		[125,	"$",	"ro",	"g",	"Used in Double Spoiler, unknown."],
	"-9928": 		[125,	"$",	"ro",	"g",	"Used in Double Spoiler, unknown."],
	"-9927": 		[125,	"$",	"ro",	"g",	"Used in Double Spoiler, unknown."],
	"-9926": 		[125,	"$",	"rw",	"g",	"Global integer variable."],
	"-9925": 		[125,	"$",	"rw",	"g",	"Global integer variable."],
	"-9924": 		[125,	"$",	"rw",	"g",	"Global integer variable."],
	"-9923": 		[125,	"$",	"rw",	"g",	"Global integer variable."],
	"-9922": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9921": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9920": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9919": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9918": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9917": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9916": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9915": 		[125,	"%",	"rw",	"g",	"Global float variable."],
	"-9914": 		[125,	"$",	"ro",	"l",	"ID of the enemy."],
	"-9913": 		[125,	"$",	"ro",	"g",	"Used in Double Spoiler, amount of photos taken."],
	"-9912": 		[125,	"$",	"ro",	"g",	"Used in Double Spoiler, unknown."],
	"-9911": 		[125,	"%",	"ro",	"g",	"Angle at which the boss moves."],
	"-9910": 		[125,	"$",	"ro",	"g",	"Unknown."],
	"-9909": 		[128,	"$",	"ro",	"l",	"Unknown."],
	"-9908": 		[13,	"$",	"ro",	"g",	"Amount of killable enemies alive (that is, doesn't include hitboxless/intangible enemies etc)."],
	"-9907": 		[13,	"$",	"ro",	"g",	"Spellcard ID, used by spell practice. Unknown meaning in LoLK."],
	"-9906": 		[15,	"$",	"ro",	"l",	"Mirror flag state, either 0 or 1. TODO: verify game version"],
	"-9905": 		null,
	"-9904": 		[15,	"$",	"ro",	"g",	"Amount of misses throughout the entire game."],
	"-9903": 		[16,	"$",	"ro",	"g",	"TH16: Selected subseason. Spring = 0, summer = 1, autumn = 2, winter = 3, extra subseason = 4.<br>[game=17]TH17: Currently active hyper. Otter = 2, rest TBD.[/game]"],
	"-9902":		[17,	"$",	"ro",	"g",	"Increases whenever you graze something, but also decreases very quickly. Used by st4 midboss."],
	"-9901":		[17,	"$",	"ro",	"g",	"Amount of tokens currently flying around the screen. Used by st5 midboss."],
	"-9900":		[17,	"$",	"ro",	"g",	"Set to 1 when player is in the state of hyperdying, that is, right after breaking a hyper. Used by st6 midboss."]
};
