const VARS = {
	"-10000": 		[10,	"$",	"ro",	"g",	"RAND",			"Random integer, very large range."],
	"-9999": 		[10,	"%",	"ro",	"g",	"RANDF",		"Random float from 0.0f to 1.0f."],
	"-9998": 		[10,	"%",	"ro",	"g",	"RANDANGLE",	"Random float from -pi to pi."],
	"-9997": 		[10,	"%",	"ro",	"l",	"FINAL_X",		"Final X position of the enemy."],
	"-9996": 		[10,	"%",	"ro",	"l",	"FINAL_Y",		"Final Y position of the enemy."],
	"-9995": 		[10,	"%",	"ro",	"l",	"ABS_X",		"Absolute X position of the enemy."],
	"-9994": 		[10,	"%",	"ro",	"l",	"ABS_Y",		"Absolute Y position of the enemy."],
	"-9993": 		[10,	"%",	"ro",	"l",	"REL_X",		"Relative X position of the enemy."],
	"-9992": 		[10,	"%",	"ro",	"l",	"REL_Y",		"Relative Y position of the enemy."],
	"-9991": 		[10,	"%",	"ro",	"g",	"PLAYER_X",		"Player's X position."],
	"-9990": 		[10,	"%",	"ro",	"g",	"PLAYER_Y",		"Player's Y position."],
	"-9989": 		[10,	"%",	"ro",	"l",	"ANGLE_PLAYER",	"Angle from the enemy to the player."],
	"-9988": 		[10,	"$",	"ro",	"l",	"TIME",			"Time elapsed since the enemy spawned, in frames."],
	"-9987": 		[10,	"%",	"ro",	"g",	"RANDF2",		"Random float from -1.0f to 1.0f."],
	"-9986": 		[10,	"$",	"ro",	"g",	"TIMEOUT",		"Set to 1 by the engine when a timeout occurs."],
	"-9985": 		[10,	"$",	"rw",	"l",	"I0",			"Local integer variable, inherited by spawned enemies."],
	"-9984": 		[10,	"$",	"rw",	"l",	"I1",			"Local integer variable, inherited by spawned enemies."],
	"-9983": 		[10,	"$",	"rw",	"l",	"I2",			"Local integer variable, inherited by spawned enemies."],
	"-9982": 		[10,	"$",	"rw",	"l",	"I3",			"Local integer variable, inherited by spawned enemies."],
	"-9981": 		[10,	"%",	"rw",	"l",	"F0",			"Local float variable, inherited by spawned enemies."],
	"-9980": 		[10,	"%",	"rw",	"l",	"F1",			"Local float variable, inherited by spawned enemies."],
	"-9979": 		[10,	"%",	"rw",	"l",	"F2",			"Local float variable, inherited by spawned enemies."],
	"-9978": 		[10,	"%",	"rw",	"l",	"F3",			"Local float variable, inherited by spawned enemies."],
	"-9977": 		[10,	"%",	"ro",	"l",	"FINAL_X2",		"Same as FINAL_X?"],
	"-9976": 		[10,	"%",	"ro",	"l",	"FINAL_Y2",		"Same as FINAL_Y?"],
	"-9975": 		[10,	"%",	"ro",	"l",	"ABS_X2",		"Same as ABS_X?"],
	"-9974": 		[10,	"%",	"ro",	"l",	"ABS_Y2",		"Same as ABS_Y?"],
	"-9973": 		[10,	"%",	"ro",	"l",	"REL_X2",		"Same as REL_X?"],
	"-9972": 		[10,	"%",	"ro",	"l",	"REL_Y2",		"Same as REL_Y?"],
	"-9971": 		[10,	"%",	"ro",	"l",	"ABS_ANGLE",	"Angle of enemy's absolute movement."],
	"-9970": 		[10,	"%",	"ro",	"l",	"REL_ANGLE",	"Angle of enemy's relative movement."],
	"-9969": 		[10,	"%",	"ro",	"l",	"ABS_SPEED",	"Speed of enemy's absolute movement."],
	"-9968": 		[10,	"%",	"ro",	"l",	"REL_SPEED",	"Speed of enemy's relative movement."],
	"-9967": 		[10,	"%",	"ro",	"l",	"ABS_ORIGIN_DIST","Distance from the origin of enemy's absolute circular movement (radius of the circle)."],
	"-9966": 		[10,	"%",	"ro",	"l",	"REL_ORIGIN_DIST","Distance from the origin of enemy's relative circular movement (radius of the circle)."],
	"-9965": 		[10,	"%",	"ro",	"g",	"PLAYER_X2",	"Same as PLAYER_X?"],
	"-9964": 		[10,	"%",	"ro",	"g",	"PLAYER_Y2",	"Same as PLAYER_Y?"],
	"-9963": 		[10,	"%",	"ro",	"g",	"BOSS_X",		"Final X position of the boss."],
	"-9962": 		[10,	"%",	"ro",	"g",	"BOSS_Y",		"Final Y position of the boss."],
	"-9961": 		[10,	"$",	"ro",	"g",	"UNKNOWN61",	"Unknown variable."],
	"-9960": 		[10,	"$",	"ro",	"g",	"RANK",			"TODO: check what this actually is."],
	"-9959": 		[10,	"$",	"ro",	"g",	"DIFF",			"Difficulty (E=0, N=1, H=2, L=3, EX=4, O=5)"],
	"-9958": 		[10,	"%",	"ro",	"l",	"FINAL_ANGLE",	"Final angle of enemy's movement."],
	"-9957": 		[10,	"$",	"ro",	"g",	"TRUE",			"Always set to 1?"],
	"-9956": 		[10,	"%",	"ro",	"l",	"ABS_ANGLE_PLAYER","Angle to the player from enemy's absolute position."],
	"-9955": 		[10,	"%",	"ro",	"l",	"REL_ANGLE_PLAYER","Angle to the player from enemy's relative position."],
	"-9954": 		[10,	"$",	"ro",	"l",	"LIFE",			"Enemy's current HP."],
	"-9953": 		[10,	"$",	"ro",	"g",	"EASY",			"Set to 1 if difficulty is easy, othewise it's 0."],
	"-9952": 		[10,	"$",	"ro",	"g",	"NORMAL",		"Set to 1 if difficulty is normal, othewise it's 0."],
	"-9951": 		[10,	"$",	"ro",	"g",	"HARD",			"Set to 1 if difficulty is hard, othewise it's 0."],
	"-9950": 		[10,	"$",	"ro",	"g",	"LUNATIC",		"Set to 1 if difficulty is lunatic, othewise it's 0."],
	"-9949": 		[11,	"$",	"rw",	"g",	"MISS_COUNT",	"Increased by 1 every time the player dies."],
	"-9948": 		[11,	"$",	"rw",	"g",	"BOMB_COUNT",	"Increased by 1 every time the player bombs."],
	"-9947": 		[11,	"$",	"rw",	"g",	"CAPTURE",		"Set to 0 when the player dies, bombs, or uses a game-specific mechanic that \"fails\" a spell."],
	"-9946": 		[11,	"$",	"ro",	"g",	"ENM_CNT_REAL",	"Amount of enemies alive (including main and MapleEnemy)."],
	"-9945": 		[11,	"$",	"ro",	"g",	"SHOTTYPE",		"Numeric value that represents player's shottype, the first shottype is 0."],
	"-9944": 		[11,	"%",	"ro",	"l",	"DIST_PLAYER",	"Distance from the enemy to the player."],
	"-9943": 		[11,	"$",	"rw",	"l",	"BI0",			"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9942": 		[11,	"$",	"rw",	"l",	"BI1",			"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9941": 		[11,	"$",	"rw",	"l",	"BI2",			"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9940": 		[11,	"$",	"rw",	"l",	"BI3",			"Local integer variable of the boss (TODO: how does it work exactly?)"],
	"-9939": 		[11,	"%",	"rw",	"l",	"BF0",			"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9938": 		[11,	"%",	"rw",	"l",	"BF1",			"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9937": 		[11,	"%",	"rw",	"l",	"BF2",			"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9936": 		[11,	"%",	"rw",	"l",	"BF3",			"Local float variable of the boss (TODO: how does it work exactly?)"],
	"-9935": 		[11,	"%",	"rw",	"l",	"F4",			"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9934": 		[11,	"%",	"rw",	"l",	"F5",			"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9933": 		[11,	"%",	"rw",	"l",	"F6",			"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9932": 		[11,	"%",	"rw",	"l",	"F7",			"Local float variable (TODO: is it inherited by spawned enemies?)"],
	"-9931": 		[12,	"$",	"ro",	"g",	"LAST_ENM_ID",	"ID of the last spawned enemy."],
	"-9930": 		[12,	"$",	"ro",	"g",	"POWER",		"Player's power (4.00 => 400)"],
	"-9929": 		[125,	"$",	"ro",	"g",	"DS1",			"Used in Double Spoiler, unknown."],
	"-9928": 		[125,	"$",	"ro",	"g",	"DS2",			"Used in Double Spoiler, unknown."],
	"-9927": 		[125,	"$",	"ro",	"g",	"DS3",			"Used in Double Spoiler, unknown."],
	"-9926": 		[125,	"$",	"rw",	"g",	"GI0",			"Global integer variable."],
	"-9925": 		[125,	"$",	"rw",	"g",	"GI1",			"Global integer variable."],
	"-9924": 		[125,	"$",	"rw",	"g",	"GI2",			"Global integer variable."],
	"-9923": 		[125,	"$",	"rw",	"g",	"GI3",			"Global integer variable."],
	"-9922": 		[125,	"%",	"rw",	"g",	"GF0",			"Global float variable."],
	"-9921": 		[125,	"%",	"rw",	"g",	"GF1",			"Global float variable."],
	"-9920": 		[125,	"%",	"rw",	"g",	"GF2",			"Global float variable."],
	"-9919": 		[125,	"%",	"rw",	"g",	"GF3",			"Global float variable."],
	"-9918": 		[125,	"%",	"rw",	"g",	"GF4",			"Global float variable."],
	"-9917": 		[125,	"%",	"rw",	"g",	"GF5",			"Global float variable."],
	"-9916": 		[125,	"%",	"rw",	"g",	"GF6",			"Global float variable."],
	"-9915": 		[125,	"%",	"rw",	"g",	"GF7",			"Global float variable."],
	"-9914": 		[125,	"$",	"ro",	"l",	"ID",			"ID of the enemy."],
	"-9913": 		[125,	"$",	"ro",	"g",	"DS_PHOTOCOUNT","Used in Double Spoiler, amount of photos taken."],
	"-9912": 		[125,	"$",	"ro",	"g",	"DS4",			"Used in Double Spoiler, unknown."],
	"-9911": 		[125,	"%",	"ro",	"g",	"ANGLE_BOSS",	"Angle at which the boss moves."],
	"-9910": 		[125,	"$",	"ro",	"g",	"UNKNOWN10",	"Unknown."],
	"-9909": 		[128,	"$",	"ro",	"l",	"UNKNOWN9",		"Unknown."],
	"-9908": 		[13,	"$",	"ro",	"g",	"ENM_CNT",		"Amount of killable enemies alive (that is, doesn't include hitboxless/intangible enemies etc)."],
	"-9907": 		[13,	"$",	"ro",	"g",	"SPELL_ID",		"Spellcard ID, used by spell practice. Unknown meaning in LoLK."],
	"-9906": 		[15,	"$",	"ro",	"l",	"MIRROR",		"Mirror flag state, either 0 or 1. TODO: verify game version"],
	"-9905": 		null,
	"-9904": 		[15,	"$",	"ro",	"g",	"MISS_COUNT_GLOBAL","Amount of misses throughout the entire game."],
	"-9903": 		[16,	"$",	"ro",	"g",	"SUBSEASON/[game=17]$HYPER[/game]",	"TH16: Selected subseason. Spring = 0, summer = 1, autumn = 2, winter = 3, extra subseason = 4.<br>[game=17]TH17: Currently active hyper. Otter = 2, rest TBD.[/game]"],
	"-9902":		[17,	"$",	"ro",	"g",	"GRAZE_RECENT",	"Increases whenever you graze something, but also decreases very quickly. Used by st4 midboss."],
	"-9901":		[17,	"$",	"ro",	"g",	"GOASTS",		"Amount of tokens currently flying around the screen. Used by st5 midboss."],
	"-9900":		[17,	"$",	"ro",	"g",	"HYPERDYING",	"Set to 1 when player is in the state of hyperdying, that is, right after breaking a hyper. Used by st6 midboss."]
};
